root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/strict
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - './tsconfig.json'
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - src/**/*.test.ts
